
name: CI Integration tests

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.yml
      DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_PASS: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - name: Build docker images
        run: docker-compose build

#      - name: set up docker
#        uses: docker/setup-buildx-action@v1
#        id: buildx
#        with:
#          install: true
#      - name: run docker file
#        run: ./run
#        continue-on-error: true
#      - name: Set up JDK 11
#        uses: actions/setup-java@v2
#        with:
#          java-version: '11'
#          distribution: 'adopt'

      - name: Integration Tests
        run: mvn -B verify serenity:aggregate --file awesome-calculator_integration_test/pom.xml
